ALTER TABLE exam ADD COLUMN score_visibility_mode VARCHAR(32) NOT NULL DEFAULT 'AFTER_TEACHER_CONFIRM';

ALTER TABLE lab ADD COLUMN score_visibility_mode VARCHAR(32) NOT NULL DEFAULT 'AFTER_TEACHER_CONFIRM';
