ALTER TABLE homework ADD COLUMN score_released BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE exam ADD COLUMN score_released BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE lab ADD COLUMN score_released BOOLEAN NOT NULL DEFAULT FALSE;
